export const assetLabels = {
  'EURUSD=X': { name: 'Euro', currency: '$', group: 'global' },
  'ESE.PA': { name: 'ETF S&P500', currency: '€', group: 'region' },
  'VERX.AS': { name: 'ETF Europe', currency: '€', group: 'region' },
  'PAASI.PA': { name: 'ETF Asie', currency: '€', group: 'region' },
  'LCUJ.DE': { name: 'ETF Japon', currency: '€', group: 'country' },
  'SXRW.DE': { name: 'ETF UK', currency: '€', group: 'country' },
  '4BRZ.DE': { name: 'ETF Brésil', currency: '$', group: 'country' },
  'SW2CHB.SW': { name: 'ETF Suisse', currency: 'CHF', group: 'country' },
  'MFA8.PA': { name: 'ETF CTA', currency: '$', group: 'hedge' },
  'PPFB.DE': { name: 'ETC Gold', currency: '€', group: 'etc' },
  'COPAP.PA': { name: 'ETC Cuivre', currency: '€', group: 'etc' },
  'BTC-USD': { name: 'Bitcoin', currency: '$', group: 'crypto' },
  'ETH-USD': { name: 'Ethereum', currency: '$', group: 'crypto' },
};